config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"``
  get "/dashboard", to: "users#dashboard"
  resources :organs, shallow: true do
    resources :reviews, only: %i[create edit update destroy]
    resources :bookings, only: %i[create update destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :organ
  belongs_to :user, optional: true
  validates :availability, presence: true
  enum availability: { free: 0, pending: 1, sold: 2 }
end

app/models/organ.rb
class Organ < ApplicationRecord
  belongs_to :user
  has_one :review
  has_one :booking, dependent: :destroy
  has_one_attached :image_url

validates :name, presence: true, length: { maximum: 55 }

  after_create :booking_creation

  validates :name, presence: true

  validates :category, presence: true
  #inclusion: { in: %w(small medium large)}

  validates :description, presence: true
  # validates :image_url, presence: true
  validates :pricing, presence: true

  def booking_creation
    Booking.create(organ: self)
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :organ
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :organs

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true, format: { with: /\A.*@.*\.com\z/ }
  validates :password, presence: true

  # Créer une méthode "average rating" relatif à un user
  # Je récupère le tableau de notes des reviews de tous ses organs (voir méthode dans le terminal)
  # J'en fais la moyenne
  # J'utilise cette méthode où j'ai besoin d'afficher cette moyenne

  def average_rating
    reviews = organs.map(&:review).compact
    return nil if reviews.empty?

    all_ratings = reviews.map(&:rating)
    all_ratings.sum.fdiv(all_ratings.count)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def update
    @booking = Booking.find(params[:id])
    if params[:action_btn] == "book"
      @booking.update(availability: 1, user: current_user)
    elsif params[:action_btn] == "accept"
      @booking.update(availability: 2, user: current_user)
    end
    respond_to |format| format.js
    # redirect_to dashboard_path, status: :see_other
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to dashboard_path, status: :see_other
  end
end

app/controllers/organs_controller.rb
class OrgansController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:query].present?
      sql_query = "name ILIKE :query OR category ILIKE :query"
      @organs = Organ.where(sql_query, query: "%#{params[:query]}%")
    else
      @organs = Organ.all
    end
  end

  def show
    @organ = Organ.find(params[:id])
  end

  def new
    @organ = Organ.new
  end

  def create
    @organ = Organ.new(organ_params)
    @organ.user = current_user
    @organ.save
    redirect_to organ_path(@organ)
  end

  def edit
    @organ = Organ.find(params[:id])
  end

  def update
    @organ = Organ.find(params[:id])
    @organ.update(organ_params)
    redirect_to organ_path(@organ)
  end

  def destroy
    @organ = Organ.find(params[:id])
    @organ.destroy
    redirect_to organs_path, status: :see_other
  end

  private

  def organ_params
    params.require(:organ).permit(:name, :category, :description, :pricing, :image_url)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @organ = Organ.find(params[:organ_id])
    @review = Review.new(review_params)
    @review.organ = @organ
    if @review.save
      redirect_to dashboard_path
    else
      # render :dashboard, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end


  private

  def review_params
    params.require(:review).permit(:comment, :rating)

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def dashboard
    @bookings = Booking.where(user: current_user)
    @review = Review.new
    @user = User.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_card_booking.html.erb
<div class="dashboard-card">
  <%= cl_image_tag booking.organ.image_url.key %>
  <div class="dashboard-booking-card-infos">
    <h4>Annonce : <%= booking.organ.name %></h4>
    <p> Catégorie : <%= booking.organ.category %></p>
    <p> Détails : <%= booking.organ.description %></p>
    <p>Prix : <%= booking.organ.pricing %>€</p>
  </div>

  <div class="dashboard-booking-card-status" id="booking-card-status-right">
    <div class="status-right align-self-start">
      <p> Statut :
        <% if booking.pending? %>
          <%= "En attente de validation" %>
        <% elsif booking.availability == "sold" %>
          <%= "Acheté" %>
        <% else %>
          <%= "" %>
        <% end %>
      </p>
      <p>Vendu par : <%= booking.organ.user.username %></p>
    </div>

    <!-- Button trigger modal -->

    <% if booking.sold? && !booking.organ.review %>

    <button type="button" class="orders-button" data-bs-toggle="modal" data-bs-target="#exampleModal">
      Rédiger un avis
    </button>

    <% elsif booking.organ.review %>

    <div class="dropdown">
      <button class="orders-button dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
        Voir mon avis
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
          <p><%= booking.organ.review.comment %></p>
          <p><%= booking.organ.review.rating %></p>
      </div>
    </div>
    <% end %>

<!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Rédiger un avis</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>





          <div class="modal-body">

            <%= simple_form_for([booking.organ, @review]) do |f| %>
              <%= f.error_notification %>
              <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

              <div class="form-inputs">
                <%= f.input :comment %>
                <%= f.input :rating %>
              </div>

          </div>






          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
              <div class="form-actions" id="save-review">
                <%= f.button :submit, "Sauvegarder" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/bookings/_card_sale.html.erb
<div class="dashboard-card">
  <div class="emoji-delete-edit">
    <%= link_to "🖊", edit_organ_path(booking.organ) %>
    <%= link_to "🗑", organ_path(booking.organ), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
  </div>
  <%= cl_image_tag booking.organ.image_url.key %>
  <div class="dashboard-booking-card-infos">
    <h4><%= booking.organ.name %></h4>
    <p> Catégorie : <%= booking.organ.category %></p>
    <p> Détails : <%= booking.organ.description %></p>
    <p>Prix : <%= booking.organ.pricing %>€</p>
  </div>

  <div class="dashboard-booking-card-status">
    <p>Statut :
      <% if booking.availability == "pending" %>
        <%= "En attente de validation" %>
      <% elsif booking.availability == "sold" %>
        <%= "Vendu" %>
      <% else %>
        <%= "" %>
      <% end %>
    </p>
    <p>Acheté par : <%= booking.user.username %></p>
    <div class="button-buyer">
      <% if booking.availability == "pending" %>
          <%= button_to "Accepter", booking_path(booking, action_btn: "accept"), class:"orders-button", id:"accept-refuse", method: :put %>
          <%= button_to "Refuser", booking_path(booking), class:"orders-button", id:"accept-refuse", method: :delete %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lebonrein</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

  </head>

  <body>

    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/footer" %>

  </body>
</html>

app/views/organs/_displayed_organs.html.erb
<% if organ.booking&.availability == "sold" %>
  <%= "" %>
<% else %>
  <div class="card-btn-container">
    <div class="card">
      <% if organ.image_url.key.present? %>
        <%= cl_image_tag organ.image_url.key, crop: :fill %>
      <% else %>
        <img src="https://www.3dnatives.com/wp-content/uploads/heart_cover-1.jpg" alt="">
      <% end %>
      <div class="card-content">
        <h2><%= organ.name.capitalize %></h2>
        <div class="card-info-price">
          <div class="card-info">
            <p>Catégorie : <%= organ.category.capitalize %></p>
            <p>
              Vendu par : <%= organ.user.username%>
              <% if organ.user.average_rating %>
                <%= "(#{organ.user.average_rating} ⭐️)" %>
              <% end %>
            </p>
            </p>
          </div>
          <h2><%= organ.pricing %>€</h2>
        </div>
      </div>
    </div>
      <%= link_to "En savoir plus", organ_path(organ), :class => "red-button" %>
  </div>
<% end %>

app/views/organs/edit.html.erb
<%= simple_form_for(@organ) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :category %>
    <%= f.input :description %>
    <%= f.input :pricing %>
    <%= f.input :image_url, as: :file %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Enregistrer", class: "btn btn-lg"  %>
  </div>
<% end %>

app/views/organs/index.html.erb
<div class="organs-banner">
  <h1>ORGANES DISPONIBLES</h1>
</div>

  <%= form_with url: organs_path, method: :get, class: "search-bar" do %>
    <%= text_field_tag :query,
      params[:query],
      class: "search-form-control form-group",
      placeholder: "Rechercher un organe"
    %>
    <%= submit_tag "Rechercher", class: "btn-search" %>
  <% end %>

<div class="cards">
  <% @organs.each do |organ| %>
    <%= render "displayed_organs", organ: organ %>
  <% end %>
</div>

app/views/organs/new.html.erb
<div class="lebonrein-container">
  <h1>Création d'une annonce</h1>

  <%= simple_form_for(@organ) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :name, label: "Nom", required: false %>
      <%= f.input :category, label: "Catégorie", required: false %>
      <%= f.input :description, required: false %>
      <%= f.input :pricing, label: "Prix", required: false %>
      <%= f.input :image_url, as: :file, label:"Photo", required: false %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, "Enregistrer", class: "btn-lg"  %>
    </div>
  <% end %>
</div>

app/views/organs/show.html.erb
<div class="show-layout lebonrein-container">
  <h1 class= "show-title"><%= @organ.name %></h1>


  <div class= "organ-content">
   <% if @organ.image_url.key.present? %>
    <%= cl_image_tag @organ.image_url.key, crop: :fill %>
    <% end %>
    <div class="organ-info">
      <p><%= @organ.category %></p>
      <p><%= @organ.description %></p>
      <p>
        <% if @organ.user != current_user && @organ.user.average_rating %>
          <%= "Vendu par : #{@organ.user.username}" %>
          <%= "(#{@organ.user.average_rating} ⭐️)" %>
        <% elsif @organ.user == current_user %>
        <% else %>
          <%= "Vendu par : #{@organ.user.username}" %>
        <% end %>
      </p>

    <div class="organ-info-bottom">
      <h2><%= @organ.pricing %>€</h2>
    </div>
     <% if @organ.user == current_user %>
      <%= link_to "Modifier", edit_organ_path, class: "btn btn-lg" %>
      <%= link_to "Supprimer", organ_path(@organ), class: "btn btn-lg" , data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
     <% elsif current_user.nil? %>
      <p>Connectez-vous pour pouvoir réserver cet organe</p>
     <% else %>
       <div class="btn-buy">
        <%= link_to "Reserver", booking_path(@organ.booking, action_btn: "book"), class: "btn btn-lg" , data: { turbo_method: :patch } %>
      </div>

      <% end %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<%= render "shared/home_banner" %>

<div class="lebonrein-container d-flex justify-content-between">

  <div class="home-buttons-left">
    <h2>ACHAT</h2>
    <p>Notre plateforme vous permet de rechercher l'organe de vos rêves et vous garantit la viabilité de votre nouvelle acquisition. Faites nous confiance et sautez le pas !
    </p>
    <%= link_to "Acheter", organs_path, class: "btn btn-lg" %>
  </div>

  <div class="home-buttons-right">
    <h2>VENTE</h2>
    <p>Vendre votre organe sur Lebonrein est un jeu d'enfant. Offrez une nouvelle vie à tous ceux qui sont dans le besoin et mettez votre altruisme à profit !</p>
    <%= link_to "Vendre", new_organ_path, class: "btn btn-lg" %>
  </div>
</div>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://cdn.dribbble.com/users/2381658/screenshots/7243590/media/f3eaf52a8a6b1cf9c4ead9419a875137.png?compress=1&resize=1600x1200&vertical=top);">
  <div class="container">
    <h1>Un organe pour une nouvelle vie !</h1>
    <h2>N°1 des marketplaces de trafic d'organes en France</h2>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
      <i class="fa-solid fa-lungs"></i> Lebonrein 2022 ©
    </div>
  <div class="footer-links">
    <a href="https://www.instagram.com/?hl=fr"><i class="fab fa-instagram"></i></a>
    <a href="https://fr-fr.facebook.com/"><i class="fab fa-facebook"></i></a>
    <a href="https://twitter.com/?lang=fr"><i class="fab fa-twitter"></i></a>
  </div>
</div>

app/views/shared/_home_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://cdn.dribbble.com/users/2381658/screenshots/7243590/media/f3eaf52a8a6b1cf9c4ead9419a875137.png?compress=1&resize=1600x1200&vertical=top);">
  <div class="container">
    <h1>Un organe pour une nouvelle vie !</h1>
    <h2>N°1 des marketplaces de trafic d'organes en France</h2>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid navbar-default">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png"%>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="nav justify-content-center">
          <li class="nav-element active">
            <%= link_to "Liste des organes", organs_path, class: "nav-link" %>
          </li>
        <% if user_signed_in? %>
          <li class="nav-element">
            <%= link_to "Créer une annonce", new_organ_path, class: "nav-link" %>
          </li>
          <li class="nav-element">
            <%= link_to "Tableau de bord", dashboard_path, class: "nav-link", data: { turbo: false } %>
          </li>
          <li class="nav-element dropdown">
            <%= image_tag "https://koreamts.com/wp-content/uploads/avatar-7.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profil", "#", class: "dropdown-item" %>
              <%= link_to "Connexion", "#", class: "dropdown-item" %>
              <%= link_to "Déconnexion", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-element">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/dashboard.html.erb
<div class="lebonrein-container">
  <div class="tabs">
    <div class="tab tab-active" id="tab-sales">
      Mes ventes
    </div>
    <div class="tab" id="tab-orders">
      Mes commandes
    </div>
  </div>


  <div class="tab-content" id="myTabContent">

    <div class="tab-pane fade show" id="tab-content-orders" role="tabpanel" aria-labelledby="home-tab">
      <% @bookings.each do |booking| %>
        <%= render "bookings/card_booking", booking: booking %>
      <% end %>
    </div>

    <div class="tab-pane fade show active" id="tab-content-sales" role="tabpanel" aria-labelledby="profile-tab">
      <% @bookings.each do |booking| %>
        <%= render "bookings/card_sale", booking: booking %>
      <% end %>
    </div>
  </div>

</div>